apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rlqa5hqns-go
  janus-idp.io/tekton: rlqa5hqns-go
  backstage.io/kubernetes-id: rlqa5hqns-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rlqa5hqns-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
